### ISSUE TITLE
[test] translate="no" is not correctly considered

### ISSUE THREAD

**Issue by m1ci** [freme-project/e-Internationalization#18] opened 2015-10-23 12:10 UTC
I sent the request:

curl -X POST --header "Content-Type: text/html" --header "Accept: text/turtle" "http://api-dev.freme-project.eu/current/e-translation/tilde?source-lang=en&target-lang=de" -d @test.html -v

Where the HTML is

    <html><head><body><p>Welcome to <span its-ta-ident-ref="http://dbpedia.org/resource/Berlin">Berlin</span>, the <span translate="yes">capital</span> of <span its-ta-ident-ref="http://dbpedia.org/resource/Germany">Germany</span>.</p></body></html>

... and I request to translate the word "capital". However, in the results this word is not translated, but the whole sentence.
The result is:

```
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix nif:   <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .
@prefix dc:    <http://purl.org/dc/elements/1.1/> .

<http://freme-project.eu/#char=0,42>
        a               nif:String , nif:RFC5147String , nif:Context ;
        nif:beginIndex  "0"^^xsd:nonNegativeInteger ;
        nif:endIndex    "42"^^xsd:nonNegativeInteger ;
        nif:isString    "Welcome to Berlin, the capital of Germany."@en ;
        dc:identifier   "1" ;
        itsrdf:target   "Berlin, Deutschland, die zu."@de .

<http://freme-project.eu/#char=34,41>
        a                     nif:String , nif:RFC5147String , nif:Phrase ;
        nif:ReferenceContext  "http://freme-project.eu/#char=0,42" ;
        nif:anchorOf          "Germany"@en ;
        nif:beginIndex        "34"^^xsd:nonNegativeInteger ;
        nif:endIndex          "41"^^xsd:nonNegativeInteger ;
        itsrdf:taIdentRef     <http://dbpedia.org/resource/Germany> .

<http://freme-project.eu/#char=11,17>
        a                     nif:String , nif:RFC5147String , nif:Phrase ;
        nif:ReferenceContext  "http://freme-project.eu/#char=0,42" ;
        nif:anchorOf          "Berlin"@en ;
        nif:beginIndex        "11"^^xsd:nonNegativeInteger ;
        nif:endIndex          "17"^^xsd:nonNegativeInteger ;
        itsrdf:taIdentRef     <http://dbpedia.org/resource/Berlin> .
```

**Comment by borriellom** [comment] 2015-10-27 10:59
ITS translate property is not currently supported by e-Internationalization.

**Comment by m1ci** [comment] 2015-10-27 12:00
thanks for clarification, 
1) but e-Internationalization can be used with e-Translation, right?

> ITS translate property is not currently supported by e-Internationalization.

Refering to http://api-dev.freme-project.eu/doc/knowledge-base/eInternationalization.html#note-on-its-tags - it can be good also to state what ITS properties are considered by e-Internationalization in addition to the information what is not supported.

**Comment by borriellom** [comment] 2015-11-03 09:25
Can I close this issue? It's not a bug. The documentation states that ITS Translate category is not supported

**Comment by borriellom** [comment] 2015-11-03 09:26
Can I close this issue? The documentation states that the ITS Translate category is not supported

**Comment by m1ci** [comment] 2015-11-03 09:55
in addition to what is NOT supported, it can be good to state also what IS supported.

**Comment by borriellom** [comment] 2015-11-04 10:59
Done.

**Closed** 2015-11-04 10:59 UTC
Labels: bug
